# Outputs generated by main.tf

output "user_login" {
    description = "Login name for ECS instance"
    value = "root"
}

output "public_ip" {
    description = "ECS instance public IP address"
    value = "${alicloud_instance.ecs-example-instance.public_ip}"
}

